name: Geocode new locations

on: issues

jobs:
  geocode:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract fields
        id: extract
        run: |
          echo "adres=test" >> $GITHUB_OUTPUT

      - name: Geocode via PDOK
        id: geo
        run: |
          echo "lat=52.37" >> $GITHUB_OUTPUT
          echo "lon=4.90" >> $GITHUB_OUTPUT

      - name: Append to community data
        run: |
          FILE="docs/data/community.js"

          sed '1s/^var.*= //' $FILE > temp.json
          sed -i '$ s/;$//' temp.json

          jq '.features += [{
            "type": "Feature",
            "properties": {
            "name": "Test locatie",
            "url": "https://example.com",
            "description": "test beschrijving"
          },
         "geometry": {
            "type": "Point",
            "coordinates": [4.90, 52.37]
          }
        }]' temp.json > updated.json

    echo "var json_community = " > $FILE
    cat updated.json >> $FILE
    echo ";" >> $FILE
