name: Geocode new locations

on:
  workflow_dispatch:

jobs:
  geocode:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Append to community data
        run: |
          FILE="docs/data/community.js"

          sed '1s/^var.*= //' $FILE > temp.json
          sed -i '$ s/;$//' temp.json

          jq '.features += [{
           "type": "Feature",
           "properties": {
             "name": "Test locatie",
             "url": "https://example.com",
             "description": "test beschrijving"
          },
          "geometry": {
          "type": "Point",
          "coordinates": [4.90, 52.37]
          }
          }]' temp.json > updated.json

       echo "var json_community = " > $FILE
       cat updated.json >> $FILE
       echo ";" >> $FILE
