name: Geocode new locations

on:
  workflow_dispatch:

jobs:
  geocode:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Append test
        run: echo "// test $(date)" >> docs/data/community.js

      - name: Commit changes
             - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          echo "STATUS BEFORE:"
          git status

          git add docs/data/community.js

          echo "STATUS AFTER ADD:"
          git status

          git commit -m "update community" || echo "nothing to commit"

          git push origin HEAD:main
